//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net.Boot.Aspnet.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Net.Boot.Aspnet.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 (function () {
        ///    $(function () {
        ///        var input = $(&apos;#input_apiKey&apos;);
        ///
        ///        input.attr(&quot;placeholder&quot;, &quot;授权码&quot;);
        ///        input.off();
        ///        input.on(&apos;change&apos;, function () {
        ///            var key = this.value;
        ///            if (key &amp;&amp; key.trim() !== &apos;&apos;) {
        ///                swaggerUi.api.clientAuthorizations.add(&quot;key&quot;, new SwaggerClient.ApiKeyAuthorization(&quot;Authentication&quot;, key, &quot;header&quot;));
        ///            }
        ///        });
        ///
        ///        setTimeout(function () {
        ///            if (window.SwaggerTranslator) {
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string authToken {
            get {
                return ResourceManager.GetString("authToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;use strict&apos;;
        ///
        ////**
        /// * Translator for documentation pages.
        /// *
        /// * To enable translation you should include one of language-files in your index.html
        /// * after &lt;script src=&apos;lang/translator.js&apos; type=&apos;text/javascript&apos;&gt;&lt;/script&gt;.
        /// * For example - &lt;script src=&apos;lang/ru.js&apos; type=&apos;text/javascript&apos;&gt;&lt;/script&gt;
        /// *
        /// * If you wish to translate some new texts you should do two things:
        /// * 1. Add a new phrase pair (&quot;New Phrase&quot;: &quot;New Translation&quot;) into your language file (for example lang/ru.js). It will be great if y [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string translator {
            get {
                return ResourceManager.GetString("translator", resourceCulture);
            }
        }
    }
}
